<html>
    <body>
        <h1>This PHP <?phpecho 'hello Wolrd!';
        ?></h1>
        <div>
        <?php
        { 
            #die;
            //
            /*
            */
        ?>
        <p>2</p>
        <?php
        }
        ?>
        <p>3</p>
        </div>
    </body>
</html>